## Create Capture-Recapture data

```{r dataCMROptions, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r librariesdataCMR, echo = FALSE}
#library(devtools)
#options(download.file.method = "wininet") or turn off VPN
#devtools::install_github('Conte-Ecology/westBrookData/getWBData')
library(data.table)
library(getWBData)
library(lubridate)
library(validate)
library(rlang)
library(stringi)
library(writexl)
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(targets)

# devtools::install_github('bletcher/getPrepareWBData')
# use this if command above doesn't work: options(download.file.method = "wininet")
#library(getPrepareWBData)
```

Get electrofishing data target for WB

```{r dataCMR_WB}

cdWB_CMR0_WB <- tar_read(eh_WB_2002_2014_target)
cdWB_CMR0_WB$data %>% group_by(riverN, cohort) %>% summarize(n = n())
cdWB_CMR0_WB$data %>% filter(enc == 1) %>% group_by(riverN, cohort) %>% summarize(n = n())

```

Get electrofishing data target for OB

```{r dataCMR_OB}

cdWB_CMR0_OB <- tar_read(eh_OB_2002_2014_target)
cdWB_CMR0_OB$data %>% group_by(riverN, cohort) %>% summarize(n = n())
cdWB_CMR0_OB$data %>% filter(enc == 1) %>% group_by(riverN, cohort) %>% summarize(n = n())

```

```{r}
# eh <- tar_read(eh_target)
# 
# fileName = paste0("eh_", stri_paste_list(vals, collapse = "_"))
# save(eh, file = paste0('./models/cmrFlow4rivers/dataOut/', fileName, '.RData'))
```

```{r }
#| fig-cap: 
#|   - "length/weight graph"




```

```{r }

```
