project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true

comments:
  hypothesis: 
    theme: clean

book:
  title: "The West Brook story"
  author: "Ben Letcher"
  date: today
  chapters:
    - index.qmd
    - part: "Targets"
      chapters:
        - vizTargets.qmd
    - part: "Get data"
      chapters: 
        - getData.qmd
        - getDataEnv.qmd
        - getDataElectro.qmd
        - getDataCMR.qmd
        - getDataWanding.qmd
        - getDataAntenna.qmd
    - part: "All data"
      chapters: 
        - dataAll.qmd
    - part: "General models"
      chapters: 
        - modelYOY.qmd
        - modelFlow.qmd
        - modelConditionFactor.qmd
        - modelGrowthInMass.qmd
    - part: "Capture-recapture models"
      chapters: 
        - modelsCMR_ft_cohort_Flow_OB.qmd
        - modelsCMR_ft_cohort_Flow_WB.qmd
    - part: "Miscallaneous/playground"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
      
  pdf:
    documentclass: scrreprt

editor: source

