project:
  type: book

book:
  title: "The West Brook story"
  author: "Ben Letcher"
  date: "today"
  chapters:
    - index.qmd
    - 01-vizTargets.qmd
    - 02-getData.qmd
    - 03-getEnvData.qmd
    - 04-getElectroData.qmd
    - 05-dataCMR.qmd
    - 06-dataWanding.qmd
    - 07-dataAntenna.qmd
    - 08-modelYOY.qmd
    - 09-modelFlow.qmd
    - 10-modelsCMR_Flow_OB.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

