project:
  type: book

book:
  title: "The West Brook story"
  author: "Ben Letcher"
  date: "today"
  chapters:
    - index.qmd
    - 02-vizTargets.qmd
    - 03-getData.qmd
    - 04-getEnvData.qmd
    - 05-getElectroData.qmd
    - 06-dataCMR.qmd
    - 07-dataWanding.qmd
    - 08-dataAntenna.qmd
    - 09-modelYOY.qmd
    - 10-modelFlow.qmd
    - 11-modelsCMR_Flow_OB.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

