project:
  type: book
  output-dir: docs

book:
  title: "The West Brook story"
  author: "Ben Letcher"
  date: today
  chapters:
    - index.qmd
    - 01-vizTargets.qmd
    - part: "Get data"
      chapters: 
        - 02-getData.qmd
        - 03-getDataEnv.qmd
        - 04-getDataElectro.qmd
        - 05-getDataCMR.qmd
        - 06-getDataWanding.qmd
        - 07-getDataAntenna.qmd
    - part: "General models"
      chapters: 
        - 08-modelYOY.qmd
        - 09-modelFlow.qmd
    - part: "Capture-recpature models"
      chapters: 
        - 10-modelsCMR_Flow_OB.qmd
        - 11-modelsCMR_Flow_4Rivers.qmd
    - references.qmd
  number-depth: 2

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

