project:
  type: book
  output-dir: docs

book:
  title: "The West Brook story"
  author: "Ben Letcher"
  date: today
  chapters:
    - index.qmd
    - vizTargets.qmd
    - part: "Get data"
      chapters: 
        - getData.qmd
        - getDataEnv.qmd
        - getDataElectro.qmd
        - getDataCMR.qmd
        - getDataWanding.qmd
        - getDataAntenna.qmd
    - part: "All data"
      chapters: 
        - dataAll.qmd
    - part: "General models"
      chapters: 
        - modelYOY.qmd
        - modelFlow.qmd
    - part: "Capture-recpature models"
      chapters: 
        - modelsCMR_Flow_OB.qmd
        - modelsCMR_Flow_4Rivers.qmd
    - references.qmd
  number-depth: 2

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
      
  pdf:
    documentclass: scrreprt

editor: source

