---
title: "All fish data"
format:
  html:
    toc: false
    echo: false
    keep-hidden: false
    code-tools: true
---

Note: need to do a full book render to get OJS functionality.

## Merge All data

```{r}
#| label: dataAllOptions
#| include: false
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
#| label: librariesdataAll
#| echo: false
#| cache: false

#library(devtools)
#options(download.file.method = "wininet") or turn off VPN
#devtools::install_github('Conte-Ecology/westBrookData/getWBData')
library(tidyverse)
library(lubridate)
library(validate)
library(targets)


# devtools::install_github('bletcher/getPrepareWBData')
# use this if command above doesn't work: options(download.file.method = "wininet")
#library(getPrepareWBData)
```

### Read merged data target
Variables in the `all data` dataset
```{r}
#| label: dataAll
#| cache: false

all <- tar_read(cdWB_all_target)
  
str(all)
#ojs_define(allOJS0 = all) can't use whole dataset, html file gets too big

# Save rData file for downloading
# save(all, file = "C:/Users/bletcher/OneDrive - DOI/projects/wbBook_quarto_targets/data/outForDownload/cdWB_all.RData")

```

```{r}
#| label: tagsAllDefineN
#| cache: false

tags <- all %>%
  group_by(tag) %>%
  summarize(n = n()) %>%
  #arrange(desc(n)) %>%
  filter(!is.na(tag))

all <- all %>% 
  left_join(tags)

allGT1500 <- all %>%
  filter(n > 500, n < 10000) |> 
  dplyr::select(tag, n, detectionDate, riverMeter, river, section, survey)


ojs_define(allOJS0 = allGT1500)
```

```{r}

# allTop10 <- all %>%
#   filter(tag %in% tags10$tag) %>%
#   select(tag, detectionDate, river, section, observedLength)
#   
#   
# ojs_define(allOJS = allTop10)
```

```{ojs}

allOJS = transpose(allOJS0)

tags = tidy(allOJS, groupBy("tag", [summarize({ n: n() })]), arrange([desc("n")]))
```

```{ojs}
//| panel: input

viewof selectTag = Inputs.select(
  tags.map((d) => d.tag),
  {
    //value: "1bf20ebcae",
    label: "Tags:",
    multiple: true
  }
)

```

Facet by river, symbol identifies survey type
```{ojs}

tagsToPlot0 = allOJS.filter((d) => selectTag.includes(d.tag))

tagsToPlot = tidy(
  tagsToPlot0,
  mutate({
    newDate: (d) => new Date(d.detectionDate)
  })
)

tagsOverTime = Plot.plot({
  marks: [
    Plot.dot(tagsToPlot, {
      x: "newDate",
      y: "riverMeter",
      stroke: "tag",
      symbol: "survey"
    }),
    Plot.line(tagsToPlot, {
      x: "newDate",
      y: "riverMeter",
      stroke: "tag"
    }),
    Plot.axisX({ ticks: "3 months" })
  ],
  
  facet: {
    data: tagsToPlot, x: "river"
  },
  // Include a legend for the color channel 
  color: {
    legend: true,
  },
  symbol: {
    legend: true
  }
})
```

One panel, symbol identifies river
```{ojs}

tagsOverTimeRiver = Plot.plot({
  marks: [
    Plot.dot(tagsToPlot, {
      x: "newDate",
      y: "riverMeter",
      stroke: "tag",
      symbol: "river"
    }),
    Plot.line(tagsToPlot, { x: "newDate", y: "riverMeter", stroke: "tag" }),
    Plot.axisX({ ticks: "3 months" })
  ],
  // Include a legend for the color channel
  color: {
    legend: true
  },
  symbol: {
    legend: true
  }
})
```


```{ojs}
selectTag
tagsToPlot
allOJS
```


```{ojs}
import {tidy, max, nDistinct, groupBy, mutate, filter, summarize, first, last, distinct, count, n, arrange, mutateWithSummary, desc, debug, sum, slice, mean, deviation, variance, meanRate, median, min, total, sliceMax, innerJoin, leftJoin, pivotLonger, pivotWider, select, rename, complete, contains, when} from "@pbeshai/tidyjs"

// Gets most recent version of Plot
Plot = import("https://esm.sh/@observablehq/plot")

```

