## Create Capture-Recapture data

```{r}
#| label: dataCMROptions
#| include: false
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
#| label: librariesdataCMR
#| echo: false
library(tidyverse)
library(targets)
library(kableExtra)
```

Data are generated in `R/getDataCMR-targets.R` [file](https://github.com/bletcher/wbBook_quarto_targets/blob/main/R/getDataCMR_targets.R)

## Get electrofishing data target WB 
West brook and 3 tributaries

```{r}
#| label: dataCMR_WB

cdWB_CMR0_WB <- tar_read(eh_WB_2002_2014_target)
str(cdWB_CMR0_WB)

#save(cdWB_CMR0_WB, file = "C:/Users/bletcher/OneDrive - DOI/projects/wbBook_quarto_targets/data/outForDownload/cdWB_CMR0_WB.RDATA")
#write.csv(cdWB_CMR0_WB$data, file = "C:/Users/bletcher/OneDrive - DOI/projects/wbBook_quarto_targets/data/outForDownload/cdWB_CMR0_WB.csv")
```

```{r}
#| label: dataCMR_WBXiaowei

# for(i in 1:length(cdWB_CMR0_WB)){
#   write.csv(cdWB_CMR0_WB[i], paste0("./data/outForXiaowei/april_18_2023/", names(cdWB_CMR0_WB)[i], ".csv"))
# }

```


```{r}
#| label: tbl-cmrWBAll
#| tbl-cap: "Count of CMR data (including 0's) by river"

cdWB_CMR0_WB$data %>% 
  group_by(riverOrdered, cohort) %>% 
  summarize(n = n()) %>%
  pivot_wider(values_from = "n", names_from = "riverOrdered") %>%
  kable() %>%
  kable_styling(full_width = T)
```


```{r}
#| label: tbl-cmrWBEnc1
#| tbl-cap: "Count of CMR data (encounters only) by river"

cdWB_CMR0_WB$data %>% 
  filter(enc == 1) %>% 
  group_by(riverOrdered, cohort) %>% 
  summarize(n = n()) %>%
  pivot_wider(values_from = "n", names_from = "riverOrdered") %>%
  kable() %>%
  kable_styling(full_width = T)
```


## Get electrofishing data target OB  
O'Bear also known as Isolated Large

```{r}
#| label: dataCMR_OB

cdWB_CMR0_OB <- tar_read(eh_OB_2002_2014_target)
```

```{r}
#| label: tbl-cmrOBAll
#| tbl-cap: "Count of CMR data (including 0's) by river"

cdWB_CMR0_OB$data %>% 
  group_by(riverOrdered, cohort) %>% 
  summarize(n = n()) %>%
  pivot_wider(values_from = "n", names_from = "riverOrdered") %>%
  kable() %>%
  kable_styling(full_width = T)
```


```{r}
#| label: tbl-cmrOBEnc1
#| tbl-cap: "Count of CMR data (encounters only) by river"

cdWB_CMR0_OB$data %>% 
  filter(enc == 1) %>% 
  group_by(riverOrdered, cohort) %>% 
  summarize(n = n()) %>%
  pivot_wider(values_from = "n", names_from = "riverOrdered") %>%
  kable() %>%
  kable_styling(full_width = T)
```



