## Get antenna data

```{r}
#| label: dataAntennaOptions
#| include: false
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
#| label: librariesdataAntenna
#| echo: false
#library(devtools)
#options(download.file.method = "wininet") or turn off VPN
#devtools::install_github('Conte-Ecology/westBrookData/getWBData')
library(tidyverse)
library(lubridate)
library(getWBData)
library(validate)
library(targets)


# devtools::install_github('bletcher/getPrepareWBData')
# use this if command above doesn't work: options(download.file.method = "wininet")
# library(getPrepareWBData)
```

## Raw data
Data are generated in `R/getDataAntenna-targets.R` [file](https://github.com/bletcher/wbBook_quarto_targets/blob/main/R/getDataAntenna_targets.R) 
Raw antenna data from the WB database (see [get data info chapter](https://bletcher.github.io/wbBook_quarto_targets/getData.html) for details) include these data frames:  

### Deployment details
```{r}
deploy <- tar_read(antennaDeployment_target)
str(deploy)
#write.csv(deploy, file = "./data/outForDownload/antenna/deploy.csv")
```

### Antenna log
```{r}
log <- tar_read(antennaLog_target)
str(log)
#write.csv(log, file = "./data/outForDownload/antenna/log.csv")
```


### Antenna status
Only dates
```{r}
status <- tar_read(antennaStatus_target)
str(status)
```

### Sites
Only dates
```{r}
sites <- tar_read(sites_target)
str(sites)
```


### Get antenna data observations target

```{r}
#| label: dataAntenna
#| cache: false
library(targets)
cdWB_antenna0 <- tar_read(cdWB_antenna0_target)
str(cdWB_antenna0)

# Save csv for downloading
# write.csv(cdWB_antenna0, file = "C:/Users/bletcher/OneDrive - DOI/projects/wbBook_quarto_targets/data/outForDownload/cdWB_antenna0.csv")
# Save rData file for downloading
# save(cdWB_antenna0, file = "C:/Users/bletcher/OneDrive - DOI/projects/wbBook_quarto_targets/data/outForDownload/cdWB_antenna0.RData")
table(cdWB_antenna0$riverMeter, cdWB_antenna0$river, cdWB_antenna0$survey)
```

